export class eventService {
  ncv = { nom: "La Nuit Centrale Verticale",
          diminutif: 'ncv',
          description: "La Nuit Centrale Verticale est une association d’étudiants de l’école CentraleSupélec. Depuis maintenant 10 ans, c’est chaque année une équipe motivée et passionnée qui vous organise cette journée mémorable.",
          couleur1: 'rgb(38,34,98)',
          couleur2: 'rgb(193,61,123)',
          couleurHover : '#fefefe',
          logoUrl: "../../assets/images/ncv_degrade.png",
          background : 'url("../../assets/images/fond_ncv_1.jpg") 50% no-repeat',
          accroche : "L'évènement emblématique de l'association",
          soustitre1 : "La ",
          soustitre2 : "plus grande compétition ",
          soustitre3 : "de voie et de bloc ",
          soustitre4 : "pour les étudiants ",
          soustitre5 : "!"};
  cvg = { nom: "Les Centrale Vertical Games",
          diminutif: 'cvg',
          description: "Les Centrale Vertical Games sont une compétition de bloc où des grimpeurs de haut niveau répondent présents : depuis plusieurs années, des membres de l’équipe de France de bloc et des grimpeurs internationaux y participent.",
          couleur1: 'rgb(20,20,20)',
          couleur2: 'rgb(201,2,69)',
          couleurHover : '#fefefe',
          logoUrl: "../../assets/images/cvg_degrade.png",
          background : 'url("../../assets/images/fond_cvg_1.jpg") 50% no-repeat',
          accroche : "Une compétition de haut niveau qui s'internationalise",
          soustitre1 : "Une compétition ouverte ",
          soustitre2 : "à tous ",
          soustitre3 : "et avec des grimpeurs de",
          soustitre4 : "niveau mondial ",
          soustitre5 : "!"};
   vt = { nom: "Vertical Team",
          diminutif: 'vt',
          description: "Vertical Team est un évènement de team building composé d’activités autour de l’escalade. Lancé cette année, cet évènement a pour but de cohésionner des membres d’une entreprise, mais aussi de rencontrer et échanger avec des étudiants de l’école CentraleSupélec.",
          couleur1: 'rgb(38,28,92)',
          couleur2: 'rgb(0,209,158)',
          couleurHover : '#fefefe',
          logoUrl: "../../assets/images/vt_degrade.png",
          background : 'url("../../assets/images/fond_vt_1.jpg") 50% no-repeat',
          accroche : "Un après-midi de cohésion au sein de l'équipe",
          soustitre1 : "Participez avec votre ",
          soustitre2 : "entreprise ",
          soustitre3 : "à notre évènement de ",
          soustitre4 : "team building",
          soustitre5 : "!"};
}